# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Start from Node.js LTS Alpine image
FROM node:lts-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and lockfile
COPY package.json package-lock.json tsconfig.json ./

# Copy source
COPY src ./src

# Install dependencies and build
RUN npm install --ignore-scripts && npm run build

# Production image
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy production build and dependencies
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules

# Expose stdio transport (stdio is default)
# Start the MCP server
CMD ["node", "build/index.js"]
